package:
    name: fms_yaml_tools
    version: 0.0.1

source:
    git_url: https://github.com/underwoo/fms_yaml_tools
    git_rev: pip.primer

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    host:
        - pip
        - python>=3.6
    run:
        - python>=3.6
        - pyyaml

test:
    commands:
        - test -f ${PREFIX}/bin/data_table_to_yaml # [unix]
        - test -f ${PREFIX}/bin/diag_table_to_yaml # [unix]
        - test -f ${PREFIX}/bin/is_valid_diag_table_yaml # [unix]
        - test -f ${PREFIX}/bin/is_valid_data_table_yaml # [unix]
        - test -f ${PREFIX}/bin/field_to_yaml # [unix]
        - ${PREFIX}/bin/data_table_to_yaml -h
        - ${PREFIX}/bin/diag_table_to_yaml -h
        - ${PREFIX}/bin/is_valid_data_table_yaml -h
        - ${PREFIX}/bin/is_valid_diag_table_yaml -h

about:
    home: https://github.com/underwoo/fms_yaml_tools
    license: LGPLv3
    summary: Suite of tools to convert ASCII FMS table files to YAML for use in FMS-based models

    description: |
      Python scripts to convert diag_table and data_table to yaml format

extra:
    recipe-maintainers:
        - underwoo

